### ISSUE TITLE
Recent Pots category filter is broken

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/Advanced-Gutenberg#132]
When changing Category filter, generates an error in console:
`Uncaught TypeError: l is not a function`

WordPress 5.5
Advanced Gutenberg 2.4.3

### Steps to reproduce:

1. Add a new page
2. Create a Recent Posts block
3. Enable browser console to see the error mentioned above after next step
4. Change the Category

### Expected result:
The posts from the selected category should be displayed only.

### Actual result:
All the posts from all the categories are displayed. 
____
Reported by a user from https://wordpress.org/support/topic/recent-posts-category-filter-failing/

**Comment by htmgarcia** [comment]
Changes to `QueryControls` component that seems related:
https://github.com/WordPress/gutenberg/compare/release/7.5...release/8.7
File: packages/components/src/query-controls/index.js

**Comment by andergmartins** [comment]
We confirmed this is a regression bug on `QueryControls` and they already fixed it for the next Gutenberg release: https://github.com/WordPress/gutenberg/pull/23419
