### ISSUE TITLE
Configuration - Open galleries in lightbox

### ISSUE THREAD

**Issue by stevejburge** [publishpress/Advanced-Gutenberg#18]
Image cannot open in lightbox after 'Open galleries in lightbox' is enabled in 'Configuration' setting.

Expected Result: Image should be able to display in lightbox

Actual Result: Image cannot open in lightbox

1) Open browser and navigate to WordPress login page
2) Enter username/email address, password and click button 'Log In'
3) In navigation bar, click menu 'Adv. Gutenburg'
4) In navigation bar, click 'Configuration'
5) In 'Configuration' section, disable "Open galleries in lightbox" by clicking on the slider button
6) In navigation bar, click menu 'Posts' and select item 'Add New'
7) In post editor, click 'Add Block' button on the top left corner 
8) Scroll down 'Content blocks' menu and click on drop down list 'Advanced Gutenberg' and click on 'Advanced Image'
9) Click 'OPEN MEDIA LIBRARY' button 
10) Click on 'Upload Files' tab
11) Click 'Select Files' button
12) Go to designated folder, select images, and click button 'Open'
13) Click 'Select' button of 'Media Library' page
14) Click 'Save Draft'
15) Click 'Preview' button
16) Click 'Publish...' button of top tool bar
17) Click 'Publish' button again
18) Click on image

<img width="304" alt="Screen Shot 2020-05-27 at 1 50 51 PM" src="https://user-images.githubusercontent.com/3868028/83054887-1aaafd80-a021-11ea-8a1a-8e65eeed0298.png">

**Comment by htmgarcia** [comment]
That setting is related to core Gallery block only. Advanced Image has its own lightbox setting while editing the block.
