### ISSUE TITLE
Configuration - Image caption

### ISSUE THREAD

**Issue by stevejburge** [publishpress/Advanced-Gutenberg#19]
Image can still show caption after the 'Image caption' is disabled in 'Configuration' setting

"Expected Result: Image should not  display caption in lightbox

Actual Result: Image can still display caption in lightbox"

"1) Open browser and navigate to WordPress login page
2) Enter username/email address, password and click button 'Log In'
3) In navigation bar, click menu 'Adv. Gutenburg'
4) In navigation bar, click 'Configuration'
5) In 'Configuration' section, disable "Open galleries in lightbox" by clicking on the slider button
6) In navigation bar, click menu 'Posts' and select item 'Add New'
7) In post editor, click 'Add Block' button on the top left corner 
8) Scroll down 'Content blocks' menu and click on drop down list 'Advanced Gutenberg' and click on 'Advanced Image'
9) Click 'OPEN MEDIA LIBRARY' button 
10) Click on 'Upload Files' tab
11) Click 'Select Files' button
12) Go to designated folder, select images, and click button 'Open'
13) Click 'Select' button of 'Media Library' page
14) Type "Hey there" as title
15) Go to 'Block Settings' on right panel of WordPress
16) In drop-down list of 'Action on click', select 'Open image in lightbox'
17) Click 'Save Draft'
18) Click 'Preview' button
19) Click 'Publish...' button of top tool bar
20) Click 'Publish' button again

<img width="300" alt="Screen Shot 2020-05-27 at 1 51 48 PM" src="https://user-images.githubusercontent.com/3868028/83054995-3ca48000-a021-11ea-939d-e636e62b5e7c.png">

**Comment by htmgarcia** [comment]
Image caption is a feature for core Gallery block only. I confirm works as expected.
<img width="708" alt="Screen Shot 2020-10-13 at 17 18 32" src="https://user-images.githubusercontent.com/4999794/95922273-85fb2f00-0d78-11eb-9808-03cf324efd3d.png">

This configuration is needed to get the expected result:
<img width="929" alt="Screen Shot 2020-10-13 at 17 20 35" src="https://user-images.githubusercontent.com/4999794/95922228-6fed6e80-0d78-11eb-80ea-c03bba08ebb0.png">
<img width="1008" alt="Screen Shot 2020-10-13 at 17 21 39" src="https://user-images.githubusercontent.com/4999794/95922319-a1fed080-0d78-11eb-9839-858f70c15a4d.png">
