### ISSUE TITLE
Block Settings - Enable blocks spacing & Blocks spacing (px)

### ISSUE THREAD

**Issue by stevejburge** [publishpress/Advanced-Gutenberg#20]
Vertical block spacing is the same as default '0 px' even when it is enabled and set to '200 px' 

"Expected Result: Blocks should have more vertical spacing between them

Actual Result: Vertical spacing between blocks remains the same as default at '0 px'"

"1) Open browser and navigate to WordPress login page
2) Enter username/email address, password and click button 'Log In'
3) In navigation bar, click menu 'Adv. Gutenburg'
4) In navigation bar, click 'Configuration'
5) In 'Block Settings' section, enable 'Enable blocks spacing' and set 'Blocks spacing (px)' as '200'
6) In navigation bar, click menu 'Posts' and select item 'Add New'
7) In post editor, click 'Add Block' button on the top left corner 
8) Scroll down 'Content blocks' menu and click on drop down list 'Advanced Gutenberg' and click on 'Advanced Image'
9) Click 'OPEN MEDIA LIBRARY' button 
10) Click on 'Upload Files' tab
11) Click 'Select Files' button
12) Go to designated folder, select images, and click button 'Open'
13) Click 'Select' button of 'Media Library' page
14) Repeat steps 7 to 13
15) Click 'Save Draft'
16) Click 'Preview' button
17) Click 'Publish...' button of top tool bar
18) Click 'Publish' button again

<img width="299" alt="Screen Shot 2020-05-27 at 1 53 21 PM" src="https://user-images.githubusercontent.com/3868028/83055148-74132c80-a021-11ea-9087-81833ca03de7.png">

**Comment by htmgarcia** [comment]
The fix is still working as expected. Re-open if any issue come up.
