### ISSUE TITLE
Email & Form - Email Settings, and Contact form 

### ISSUE THREAD

**Issue by stevejburge** [publishpress/Advanced-Gutenberg#21]
Email & Form - Email Settings, and Contact form 

A completed contact form does not send any email notification based on email settings

"Expected Result: Email notificatin should be sent to site owner based on email settings upon a form completion

Actual Result: No email notificatin is sent to site owner upon a form completion"

"1) Open browser and navigate to WordPress login page
2) Enter username/email address, password and click button 'Log In'
3) In navigation bar, click menu 'Adv. Gutenburg'
4) In navigation bar, click 'EMAIL & FORM' and select 'EMAIL SETTINGS'
5) Enter ReCaptcha v3's site key into text field of 'reCAPTCHA Site Key (required)'
6) Enter Sender name, Sender email, Email title, and Email receiver in the text fields
7) Click 'SAVE' button
8) 3) In navigation bar, click menu 'Pages' and select item 'Add New'
9) In page editor, click 'Add Block' button on the top left corner 
10) Scroll down 'Content blocks' menu and click on drop down list 'Advanced Gutenberg' and click on 'Contact Form'
11) Click 'Save Draft'
12) Click 'Preview' button
13) Click 'Publish...' button of top tool bar
14) Click 'Publish' button again
15) Enter name, valid email address, and message into the text fields
16) Click 'Submit' button
17) Check inbox of receiver email

Note: No email notification is received in inbox after the contact form is completed and submitted"

**Comment by htmgarcia** [comment]
Tested and works fine.
<img width="490" alt="Screen Shot 2020-10-13 at 18 35 54" src="https://user-images.githubusercontent.com/4999794/95927018-4dad1e00-0d83-11eb-8581-8ee8dbf0f3a0.png">
