### ISSUE TITLE
Email & Form - Forms ReCaptcha

### ISSUE THREAD

**Issue by stevejburge** [publishpress/Advanced-Gutenberg#22]
ReCaptcha v3 is displayed with an error message in contact form

"Expected Result: ReCaptcha v3 should be properly installed and displayed in contact form

Actual Result: ReCaptcha v3 is displayed with an error message "ERROR for site owner: Invalid key type" in contact form"

"Prerequiste: Register for Google ReCaptcha v3 to obtain the site and secret keys

1) Open browser and navigate to WordPress login page
2) Enter username/email address, password and click button 'Log In'
3) In navigation bar, click menu 'Adv. Gutenburg'
4) In navigation bar, click 'EMAIL & FORM' and select 'FORMS RECAPTCHA'
5) Enter ReCaptcha v3's site key into text field of 'reCAPTCHA Site Key (required)'
6) Enter ReCaptcha v3's secret key into text field of 'reCAPTCHA Secret Key (required)'
7) Click 'SAVE' button
8) 3) In navigation bar, click menu 'Pages' and select item 'Add New'
9) In page editor, click 'Add Block' button on the top left corner 
10) Scroll down 'Content blocks' menu and click on drop down list 'Advanced Gutenberg' and click on 'Contact Form'
11) Click 'Save Draft'
12) Click 'Preview' button
13) Click 'Publish...' button of top tool bar
14) Click 'Publish' button again
15) Click on image"

**Comment by htmgarcia** [comment]
reCaptcha is working fine.
