### ISSUE TITLE
In "Advanced Tab" block, the text color doar not change

### ISSUE THREAD

**Issue by JulieBanu** [publishpress/Advanced-Gutenberg#26]
Step 1:   Install and activate "Advanced Gutenberg" plugin
Step 2:   Go to a publish post and click edit
Step 3:   Click "Add Block", represented by the "+" sign
Step 4:   Select "Advanced Tab" option
Step 5:   Write a text in the body
Step 6:   Change the color of the text
 
![image](https://user-images.githubusercontent.com/62157750/83573706-dddb7c80-a4e0-11ea-8c0b-13cb09c204fc.png)

Note:   the text color stays the same

**Comment by htmgarcia** [comment]
Tested and color change works fine.
