### ISSUE TITLE
In "Images Slider" block, after activating "Enable RTL" images dissapear 

### ISSUE THREAD

**Issue by JulieBanu** [publishpress/Advanced-Gutenberg#34]
Step 1:   Install and activate "Advanced Gutenberg" plugin
--
Step 2:   Go to a publish post and click edit
Step 3:   Click "Add Block", represented by the "+" sign
Step 4:   Select "Images Slider" option
Step 5:   Add a few images
Step 6:   Click "Enable RTL"

Note 1:   The images does not appear

![image](https://user-images.githubusercontent.com/62157750/83818802-19ab4900-a67d-11ea-8fb4-d1b44a043a49.png)

Note 2: If   "enable RTL" is deactivated, images show up

**Comment by htmgarcia** [comment]
Works fine when the site uses a RTL language:
<img width="1283" alt="Screen Shot 2020-10-14 at 11 44 21" src="https://user-images.githubusercontent.com/4999794/96019900-d7f09300-0e12-11eb-930a-970f2a30ec55.png">
