### ISSUE TITLE
In "Info Box" block, after updating the post, the position of the title is a bit different from the editing post

### ISSUE THREAD

**Issue by JulieBanu** [publishpress/Advanced-Gutenberg#42]
Step 1:   Install and activate "Advanced Gutenberg" plugin
Step 2:   Go to a publish post and click edit
Step 3:   Click "Add Block", represented by the "+" sign
Step 4:   Select "Info Box" option
Step 5:   Open "Icon Settings" menu
Step 6:   From "Icon Selection" drop down menu, select an icon
Step 7:   Change the "Icon Color", "Icon Size",   "Background", "Border Color", "Border Width"   and "Border Radius"
Step 8:   Open "Title Settings" menu
Step 9:   Change the "Color", "Font Size", "Line Height"
Step 10:   Select "HTML Tag" to H4
Step 11:   Click "Update" post
Step 12:   Click "View Post"
 
Note:   After making all the changes and clicking update, the title it shows   different from the "editing" post, (the title is over the text)

Note: Picture before update, in editing mode:
![image](https://user-images.githubusercontent.com/62157750/84084109-b3ce0280-a997-11ea-9dd4-66b0a3d044df.png)
Note: Picture after update, in viewing mode:
![image](https://user-images.githubusercontent.com/62157750/84084137-c0eaf180-a997-11ea-989a-201095556d31.png)

**Comment by htmgarcia** [comment]
I wasn't able to reproduce the issue.
In fronted:
<img width="627" alt="Screen Shot 2020-10-14 at 12 46 01" src="https://user-images.githubusercontent.com/4999794/96025825-4df8f800-0e1b-11eb-974b-8658d7c6d522.png">

In backend:
<img width="627" alt="Screen Shot 2020-10-14 at 12 46 01" src="https://user-images.githubusercontent.com/4999794/96025837-53564280-0e1b-11eb-9f53-3101238e7dcb.png">
